# read only access to production db
common: &common
 adapter: mysql2
 database: photos_prod
 encoding: utf8
 host: zz-prod-rds.ckikxby0s3p8.us-east-1.rds.amazonaws.com
 username: zzuser
 password: funwithphotos

development:
  <<: *common

# make sure these are kept in sync with the EY servers
# NOTE: since the deploy user only has access to photos
# we need to use that database rather than the preferred
# approach of giving it a standalone database.  This is
# ok for production because the main database is an AmazonRDS instance
#
production:
  <<: *common


