#
# This is the dumping ground for generic zangzing related config.
#
#

common: &common
  basic_auth_user: "zzadmin"
  basic_auth_password: "1001results"
  gecko_user: "zzgecko"
  gecko_password: "X"   # They always append X as the password
  ga_user: "webmaster@zangzing.com"
  ga_password: "share1001photos"
  ga_web_property_id: "UA-18597985-1"
  ga_stats_start_date: "Sep-20-2010"

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

