#
# This is the dumping ground for generic zz environment related stuff
# I got tired of creating new .yml files for every little switch so
# we can put the bulk of them here from now on.
#


common: &common
  basic_auth_user: "zzadmin"
  basic_auth_password: "1001results"

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

